// MUI WRAPPER - ZENTRALISIERE ALLE MUI-IMPORTS
// Das BEFOLGT die Import Governance Regel aus AI_PROJECT_CONTEXT.md

// Basis Material-UI Components
export {
  Button as MuiButton,
  IconButton as MuiIconButton,
  CircularProgress,
  Typography as MuiTypography,
  TextField as MuiTextField,
  Card as MuiCard,
  CardHeader as MuiCardHeader,
  CardContent as MuiCardContent,
  CardActions as MuiCardActions,
  Divider as MuiDivider,
  Chip as MuiChip,
  Avatar as MuiAvatar,
  Badge as MuiBadge,
  Menu as MuiMenu,
  MenuItem as MuiMenuItem,
  List as MuiList,
  ListItem as MuiListItem,
  ListItemButton as MuiListItemButton,
  ListItemText as MuiListItemText,
  ListItemIcon as MuiListItemIcon,
  // Layout Components
  Box,
  Container,
  Grid,
  Stack,
  Paper,
  // Navigation
  Tabs as MuiTabs,
  Tab as MuiTab,
  Breadcrumbs as MuiBreadcrumbs,
  Link as MuiLink,
  // Feedback
  Alert as MuiAlert,
  Dialog as MuiDialog,
  DialogTitle as MuiDialogTitle,
  DialogContent as MuiDialogContent,
  DialogActions as MuiDialogActions,
  Snackbar as MuiSnackbar,
  // Data Display
  Table as MuiTable,
  TableBody as MuiTableBody,
  TableCell as MuiTableCell,
  TableContainer as MuiTableContainer,
  TableHead as MuiTableHead,
  TableRow as MuiTableRow,
  TablePagination as MuiTablePagination,
  // Form Components
  FormControl as MuiFormControl,
  FormLabel as MuiFormLabel,
  FormHelperText as MuiFormHelperText,
  InputLabel as MuiInputLabel,
  OutlinedInput as MuiOutlinedInput,
  FilledInput as MuiFilledInput,
  InputAdornment as MuiInputAdornment,
  Switch as MuiSwitch,
  Checkbox as MuiCheckbox,
  Radio as MuiRadio,
  RadioGroup as MuiRadioGroup,
  FormControlLabel as MuiFormControlLabel,
  Select as MuiSelect,
  // Progress & Loading
  LinearProgress as MuiLinearProgress,
  Skeleton as MuiSkeleton,
  // Surfaces
  AppBar as MuiAppBar,
  Toolbar as MuiToolbar,
  Drawer as MuiDrawer,
  Accordion as MuiAccordion,
  AccordionSummary as MuiAccordionSummary,
  AccordionDetails as MuiAccordionDetails,
  // Utilities
  Tooltip as MuiTooltip,
  Popover as MuiPopover,
  Modal as MuiModal,
  Backdrop as MuiBackdrop,
  Fade as MuiFade,
  Grow as MuiGrow,
  Slide as MuiSlide,
  Zoom as MuiZoom,
  Collapse as MuiCollapse,
  // Icons
  Icon as MuiIcon,
  SvgIcon as MuiSvgIcon,
  // Theme und Styling
  Theme,
  ThemeProvider,
  createTheme,
  styled,
  useTheme,
  makeStyles,
  withStyles,
  // CSS Baseline - für Box-Sizing Reset
  CssBaseline,
  // Utils und CSS Utilities
  darken,
  lighten,
  fade,
  alpha,
  emphasize,
  useMediaQuery,
  // Deprecated - aber für Kompatibilität
  createStyles,
} from '@mui/material'

export type {
  ButtonProps as MuiButtonProps,
  IconButtonProps as MuiIconButtonProps,
  TypographyProps as MuiTypographyProps,
  TextFieldProps as MuiTextFieldProps,
  CardProps as MuiCardProps,
  CardHeaderProps as MuiCardHeaderProps,
  CardContentProps as MuiCardContentProps,
  ChipProps as MuiChipProps,
  AvatarProps as MuiAvatarProps,
  BadgeProps as MuiBadgeProps,
  MenuProps as MuiMenuProps,
  MenuItemProps as MuiMenuItemProps,
  ListProps as MuiListProps,
  ListItemProps as MuiListItemProps,
  ListItemButtonProps as MuiListItemButtonProps,
  ListItemTextProps as MuiListItemTextProps,
  AlertProps as MuiAlertProps,
  DialogProps as MuiDialogProps,
  TabsProps as MuiTabsProps,
  TabProps as MuiTabProps,
  BoxProps,
  ContainerProps,
  GridProps,
  SelectProps as MuiSelectProps,
  FormControlProps as MuiFormControlProps,
  SwitchProps as MuiSwitchProps,
  CheckboxProps as MuiCheckboxProps,
  RadioProps as MuiRadioProps,
  DialogTitleProps as MuiDialogTitleProps,
  AccordionProps as MuiAccordionProps,
} from '@mui/material'